apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-echo-headers
  labels:
    app: nginx-echo-headers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-echo-headers
  template:
    metadata:
      labels:
        app: nginx-echo-headers
    spec:
      containers:
      - name: nginx-echo-headers
        image: brndnmtthws/nginx-echo-headers
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-echo-headers-service
  namespace: default
spec:
  selector:
    app: nginx-echo-headers
  ports:
  - port: 8080


