apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helmi
  namespace: default
spec:
  rules:
  - host: helmi.<your cluster base dn>
    http:
      paths:
      - backend:
          serviceName: helmi 
          servicePort: 5000
        path: /

